# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _example
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class Pos(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Pos, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Pos, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _example.Pos_x_set
    __swig_getmethods__["x"] = _example.Pos_x_get
    if _newclass:x = _swig_property(_example.Pos_x_get, _example.Pos_x_set)
    __swig_setmethods__["y"] = _example.Pos_y_set
    __swig_getmethods__["y"] = _example.Pos_y_get
    if _newclass:y = _swig_property(_example.Pos_y_get, _example.Pos_y_set)
    def __init__(self, *args): 
        this = _example.new_Pos(*args)
        try: self.this.append(this)
        except: self.this = this
    def __add__(*args): return _example.Pos___add__(*args)
    def __sub__(*args): return _example.Pos___sub__(*args)
    def __mul__(*args): return _example.Pos___mul__(*args)
    def __div__(*args): return _example.Pos___div__(*args)
    __swig_getmethods__["create_from_min"] = lambda x: _example.Pos_create_from_min
    if _newclass:create_from_min = staticmethod(_example.Pos_create_from_min)
    __swig_getmethods__["create_from_max"] = lambda x: _example.Pos_create_from_max
    if _newclass:create_from_max = staticmethod(_example.Pos_create_from_max)
    __swig_destroy__ = _example.delete_Pos
    __del__ = lambda self : None;
Pos_swigregister = _example.Pos_swigregister
Pos_swigregister(Pos)
Pos_create_from_min = _example.Pos_create_from_min
Pos_create_from_max = _example.Pos_create_from_max

increment = _example.increment


